#!/bin/sh

### BEGIN INIT INFO
# Provides:        boxitserver
# Required-Start:  $network  $syslog
# Required-Stop:   $network  $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start boxit-server
### END INIT INFO


case "$1" in
   start)
      echo "Clearing tmp folders..."
      rm -fr /var/tmp/boxit/*

      echo "Starting boxit server..."
      su boxit -c /usr/bin/boxit-server &>/var/log/boxitserver.log &
      ;;
   stop)
      echo "Stoppe fuchsserver..."
      killall boxit-server
      ;;
   restart|reload|force-reload)
   $0 stop
   sleep 1
   $0 start
      ;;
   *)
      echo "Usage: /etc/init.d/boxitserver (start|stop)"
      exit 1
      ;;
esac
exit 0

