#!/bin/sh

### BEGIN INIT INFO
# Provides:        boxit-server
# Required-Start:  $network  $syslog
# Required-Stop:   $network  $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start boxit-server
### END INIT INFO


case "$1" in
   start)
      echo "Clearing tmp folders..."
      rm -fr /var/tmp/boxit

      echo "Starting boxit server..."
      su boxit -c /usr/bin/boxit-32-server &>/var/repo/boxit-32-server.log &
      ;;
   stop)
      echo "Stopping boxit server..."
      killall boxit-32-server
      ;;
   restart|reload|force-reload)
   $0 stop
   sleep 1
   $0 start
      ;;
   *)
      echo "Usage: /etc/init.d/boxit-32-server (start|stop)"
      exit 1
      ;;
esac
exit 0

